version: '3.3'

services:
  mysql:
      image: mysql:5.7
      container_name: 'my_sqldb'
      restart: always
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: '123QWEasd'
        MYSQL_ROOT_PASSWORD: '123QWEasd'
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - mysql-db:/var/lib/mysql

  mongo:
    image: mongo:latest
    container_name: 'my_mongodb'
    environment:
      MONGO_INITDB_DATABASE: orders
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: 123QWEasd
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/db

  neo4j:
    image: neo4j:3.4
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/streams
      NEO4J_dbms_logs_debug_level: DEBUG
    ports:
      - '7474:7474'
      - '6477:6477'
      - '7687:7687'
    volumes:
      - neo4j-plugins:/plugins
      - neo4j-data:/data
      - neo4j-conf:/conf
      - neo4j-logs:/logs

volumes:
  mysql-db:
  mongo-db:
  neo4j-plugins:
  neo4j-data:
  neo4j-conf:
  neo4j-logs: