spring:
  profiles:
    active: development # <1>
---
spring:
  profiles: development # <2>
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db
    username: user
    password: 123QWEasd
---
spring:
  profiles: test # <3>
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE