spring:
  profiles:
    active: development
---
spring:
  profiles: development
  redis:
    host: localhost
    port: 6379
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db?useSSL=false
    username: user
    password: 123QWEasd
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    database: H2